export enum MerchantOnboardingErrorCode {
  MERCHANT_ONBOARDING_APPLICATION_ALREADY_EXISTS = 'MERCHANT_ONBOARDING_APPLICATION_ALREADY_EXISTS',
  MERCHANT_ONBOARDING_REGISTRATION_ALREADY_EXISTS = 'MERCHANT_ONBOARDING_REGISTRATION_ALREADY_EXISTS',
  MERCHANT_ONBOARDING_REFERENCE_DATA_STALE = 'MERCHANT_ONBOARDING_REFERENCE_DATA_STALE',
  MERCHANT_ONBOARDING_TERMS_VERSION_STALE = 'MERCHANT_ONBOARDING_TERMS_VERSION_STALE',
}
