export const HTTP_CONFIG_DEFAULTS = Object.freeze({
  NODE_ENV: 'development',
  HTTP_CONNECTION_TIMEOUT_MS: 10_000,
  HTTP_KEEP_ALIVE_TIMEOUT_MS: 72_000,
  HTTP_REQUEST_TIMEOUT_MS: 30_000,
  HTTP_BODY_LIMIT_BYTES: 1_048_576,
  HTTP_PLUGIN_TIMEOUT_MS: 10_000,
  PORT: 4000,
  WORKER_PORT: 4001,
});

export const DATABASE_CONFIG_DEFAULTS = Object.freeze({
  DATABASE_SSL_REJECT_UNAUTHORIZED: true,
});

export const REDIS_CONFIG_DEFAULTS = Object.freeze({
  REDIS_TLS_REJECT_UNAUTHORIZED: true,
  REDIS_CONNECT_TIMEOUT_MS: 10_000,
  REDIS_COMMAND_TIMEOUT_MS: 5_000,
  REDIS_MAX_RETRIES_PER_REQUEST: 2,
  REDIS_RETRY_BASE_DELAY_MS: 100,
  REDIS_RETRY_MAX_DELAY_MS: 2_000,
  REDIS_ENABLE_OFFLINE_QUEUE: true,
});

export const AUTH_CONFIG_DEFAULTS = Object.freeze({
  AUTH_ACCESS_TOKEN_TTL_SECONDS: 900,
  AUTH_REFRESH_TOKEN_TTL_SECONDS: 60 * 60 * 24 * 30,
  AUTH_EMAIL_VERIFICATION_TOKEN_TTL_SECONDS: 60 * 60 * 24,
  AUTH_PASSWORD_RESET_TOKEN_TTL_SECONDS: 60 * 30,
  AUTH_EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS: 60,
  AUTH_EMAIL_VERIFICATION_RESEND_IP_MAX_ATTEMPTS: 30,
  AUTH_EMAIL_VERIFICATION_RESEND_IP_WINDOW_SECONDS: 5 * 60,
  AUTH_EMAIL_VERIFICATION_RESEND_IP_BLOCK_SECONDS: 15 * 60,
  AUTH_PASSWORD_RESET_REQUEST_COOLDOWN_SECONDS: 60,
  AUTH_PASSWORD_RESET_REQUEST_IP_MAX_ATTEMPTS: 20,
  AUTH_PASSWORD_RESET_REQUEST_IP_WINDOW_SECONDS: 5 * 60,
  AUTH_PASSWORD_RESET_REQUEST_IP_BLOCK_SECONDS: 15 * 60,
  AUTH_PASSWORD_MIN_LENGTH: 10,
  AUTH_LOGIN_MAX_ATTEMPTS: 10,
  AUTH_LOGIN_WINDOW_SECONDS: 60,
  AUTH_LOGIN_BLOCK_SECONDS: 15 * 60,
});

export const USERS_CONFIG_DEFAULTS = Object.freeze({
  USERS_PROFILE_IMAGE_UPLOAD_USER_MAX_ATTEMPTS: 20,
  USERS_PROFILE_IMAGE_UPLOAD_USER_WINDOW_SECONDS: 60 * 60,
  USERS_PROFILE_IMAGE_UPLOAD_USER_BLOCK_SECONDS: 15 * 60,
  USERS_PROFILE_IMAGE_UPLOAD_IP_MAX_ATTEMPTS: 60,
  USERS_PROFILE_IMAGE_UPLOAD_IP_WINDOW_SECONDS: 5 * 60,
  USERS_PROFILE_IMAGE_UPLOAD_IP_BLOCK_SECONDS: 15 * 60,
  USERS_PROFILE_IMAGE_UPLOAD_EXPIRE_DELAY_SECONDS: 2 * 60 * 60,
});
