export enum AuthErrorCode {
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_PASSWORD_NOT_SET = 'AUTH_PASSWORD_NOT_SET',
  AUTH_CURRENT_PASSWORD_INVALID = 'AUTH_CURRENT_PASSWORD_INVALID',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_REUSED = 'AUTH_REFRESH_TOKEN_REUSED',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_SESSION_REVOKED = 'AUTH_SESSION_REVOKED',
  AUTH_EMAIL_VERIFICATION_TOKEN_INVALID = 'AUTH_EMAIL_VERIFICATION_TOKEN_INVALID',
  AUTH_EMAIL_VERIFICATION_TOKEN_EXPIRED = 'AUTH_EMAIL_VERIFICATION_TOKEN_EXPIRED',
}
